DigiStore.Web/Areas/Admin/Controllers/SellerController.cs
using System.Threading.Tasks;
using DigiStore.Application.Services.Interfaces;
using DigiStore.Domain.ViewModels.Common;
using DigiStore.Domain.ViewModels.Seller;
using DigiStore.Web.Http;
using DigiStore.Web.Security;
using Microsoft.AspNetCore.Mvc;

namespace DigiStore.Web.Areas.Admin.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class SellerController : AdminBaseController
    {
        #region Constructor
        private readonly ISellerService _sellerService;
        public SellerController(ISellerService sellerService)
        {
            _sellerService = sellerService;
        }
        #endregion

        #region SellerRequestList
        [PermissionChecker(2)]
        public async Task<IActionResult> SellerRequests(FilterSellerViewModel filterSeller)
        {
            return View(await _sellerService.FilterSeller(filterSeller));
        }
        #endregion

        #region AcceptSellerRequest
        [PermissionChecker(3)]
        public async Task<IActionResult> AcceptSellerRequest(int id)
        {
            var result = await _sellerService.AcceptSellerRequest(id);
            if (result)
            {
                return JsonResponseStatus.SendStatus(
                    JsonResponseStatusType.Success,
                    "درخواست مورد نطر با موفقیت ثبت شد",
                    null
                );
            }
            return JsonResponseStatus.SendStatus(
                JsonResponseStatusType.Danger,
                "اطلاعاتی با این مشخصات یافت نشد",
                null
            );
        }
        #endregion

        #region RejectSellerRequest
        [PermissionChecker(4)]
        [HttpPost,ValidateAntiForgeryToken]
        public async Task<IActionResult> RejectSellerRequest(RejectItemViewModel rejectItem)
        {
            var result = await _sellerService.RejectItem(rejectItem);
            if (result)
            {
                return JsonResponseStatus.SendStatus(
                    JsonResponseStatusType.Success,
                    "درخواست مورد نطر  رد  شد",
                    rejectItem
                );
            }
            return JsonResponseStatus.SendStatus(
                JsonResponseStatusType.Danger,
                "اطلاعاتی با این مشخصات یافت نشد",
                null
            );
        }
        #endregion

        #region SellerDetials
        [PermissionChecker(5)]
        [HttpGet("seller-detials")]
        public async Task<IActionResult> SellerDetials(int sellerId)
        {
            var seller = await _sellerService.SellerDetailsBySellerId(sellerId);
            if (seller == null) return NotFound();
            return View(seller);
        }
        #endregion
    }
}

DigiStore.Web/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using DigiStore.Application.Extensions;
using DigiStore.Application.Services.Interfaces;
using DigiStore.Domain.ViewModels.FavoriteProductUser;
using DigiStore.Domain.ViewModels.Product;
using DigiStore.Domain.ViewModels.ProductComment;
using DigiStore.Web.Http;
using DigiStore.Web.PresentationExtensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using HttpExtensions = DigiStore.Web.HttpContext.HttpExtensions;

namespace DigiStore.Web.Controllers
{
    public class ProductController : SiteBaseController
    {
        #region Constructor
        private readonly IProductService _productService;
        private readonly IBranadService _branadService;
        public ProductController(IProductService productService, IBranadService branadService)
        {
            _productService = productService;
            _branadService = branadService;
        }
        #endregion

        #region ProductSearch
        [HttpGet("ProductSearch")]
        public async Task<IActionResult> ProductSearch(FilterProductViewModel filterProduct)
        {

            filterProduct.TakeEntity = 12;
            filterProduct.FilterProductState = FilterProductState.Accepted;
            ViewBag.ProductCategories = await _productService.GetAllActiveProductCategory();
            ViewBag.ProductBrands = await _branadService.GetAllBrands();
            ViewBag.SelectedCateGory = filterProduct.SelectedPrductCategories;
            ViewBag.SelectedBrands = filterProduct.Selectedbrand;
            ViewBag.SearchName = filterProduct.Name;
            return View(await _productService.FilterForSiteSearch(filterProduct));
        }
        #endregion

        #region Show Product Detials
        [HttpGet("products/{productId}/{title}")]
        public async Task<IActionResult> ProductDetail(int productId, string title)
        {
            var product = await _productService.GetProductDetail(productId);
            if (product == null) return NotFound();
            ViewBag.IsExistThisProductInUserfavortitList =
                await _productService.IsExistThisProductInUserFavoritList(productId, User.GetUserId());
            return View(product);
        }
        #endregion

        #region Visited
        [HttpGet("visited/{produtId}")]
        public async Task Visited(int produtId)
        {
            if (produtId != 0)
            {
                await _productService.AddProductVisited(produtId, HttpExtensions.GetUserIp(HttpContext),
                    IdentityExtensions.GetUserId(User));
            }
        }
        #endregion

        #region add to favorit Product
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> AddProductToFavorit(CreateIFavoriteProductUserViewModel createIFavoriteProductUser)
        {
            if (ModelState.IsValid)
            {
                var res = await _productService.CreateIFavoriteProductUser(createIFavoriteProductUser,
                    User.GetUserId());

                if (res)
                {
                    return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success,
                        SuccessMessage = "محصول مورد نظر با موقیت ثبت شد", null);
                }
                return JsonResponseStatus.SendStatus(JsonResponseStatusType.Danger,
                    SuccessMessage = "خطا در ثبت اطلاعات", null);
            }
            return JsonResponseStatus.SendStatus(JsonResponseStatusType.Danger,
                SuccessMessage = "خطا در ثبت اطلاعات", null);
        }
        #endregion

        #region ProductCommnet
        [HttpGet("add-product-commnet/{productId}")]
        public async Task<IActionResult> ProductCommnet(int productId)
        {
            var product = await _productService.GetProductByProductId(productId);
            if (product == null) return NotFound();
            ViewBag.Product = product;
            return View(new CreateProductCommnetViewModel() { ProductId = productId });
        }
        [HttpPost("add-product-commnet/{productId}")]
        public async Task<IActionResult> ProductCommnet(CreateProductCommnetViewModel createProductCommnet)
        {
            var product = await _productService.GetProductByProductId(createProductCommnet.ProductId);
            if (product == null) return NotFound();
            if (ModelState.IsValid)
            {
                var res = await _productService.CreateProductCommnet(createProductCommnet, User.GetUserId());
                switch (res)
                {
                    case CreateProductCommnetResult.Error:
                        TempData[ErrorMessage] = "خطا در ثبت اطلاعات";
                        break;
                    case CreateProductCommnetResult.NotFoundProduct:
                        TempData[ErrorMessage] = "محصولی با این مشخصات یافت نشد";
                        break;
                    case CreateProductCommnetResult.Success:
                        TempData[SuccessMessage] = "کاربر گرامی نظر شما با موفقیت ثبت شد.";
                        TempData[InfoMessage] = "از اینکه به محصولات سایت ما توجه می کنید بی نهایت سپاس گذاریم";
                        return RedirectToAction("ProductDetail",
                            new { @productId = createProductCommnet.ProductId, @title = product.Name.FixTextForUrl() });
                }
            }
            ViewBag.Product = product;
            return View(createProductCommnet);
        }
        #endregion

        #region FilterProdutComment
        [HttpGet("filterProductComment/{productId}")]
        public async Task<IActionResult> FilterProdutComment(int productId, FilterProductCommentViewModel filterProductComment)
        {
            filterProductComment.ProductId = productId;
            return View(await _productService.filterFilterProductComment(filterProductComment));
        }

        #endregion

    }
}

DigiStore.Web/Areas/Admin/Views/Shared/Components/SidebarMenu/SidebarMenu.cshtml
   <!--- Sidemenu -->
<div id="sidebar-menu">
    <ul>


        <li>
            <a asp-controller="Home" asp-action="Index" asp-area="Admin" class="waves-effect active"><i class="zmdi zmdi-view-dashboard"></i> <span> داشبورد </span> </a>
        </li>

        <li>
            <a asp-controller="Seller" asp-action="SellerRequests" asp-area="Admin" class="waves-effect"><i class="zmdi zmdi-store"></i> <span> در خواست های فروشندگی </span> </a>
        </li>

        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-account"></i> <span> مدیریت کاربران </span> <span class="menu-arrow"></span></a>
            <ul class="list-unstyled">
                <li><a asp-controller="UserManagement" asp-action="Index" asp-area="Admin">لیست کاربران</a></li>
                <li><a asp-controller="UserManagement" asp-action="CreateUser" asp-area="Admin">ایجاد کاربر جدید</a></li>
            </ul>
        </li>

        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect"><i class="ti-hand-point-left"></i><span> مدیریت نقش ها </span><span class="menu-arrow"></span> </a>
            <ul class="list-unstyled">
                <li><a asp-controller="Role" asp-action="FilterRole" asp-area="Admin">لیست نقش های موجود</a></li>
                <li><a asp-controller="Role" asp-action="CreateRole" asp-area="Admin">ایجاد نقش جدید</a></li>
            </ul>
        </li>

        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-view-list"></i> <span> برند ها </span> <span class="menu-arrow"></span></a>
            <ul class="list-unstyled">
                <li><a asp-controller="Brand" asp-area="Admin" asp-action="BrandList">لیست برند ها</a></li>
                <li><a asp-controller="Brand" asp-area="Admin" asp-action="CreateBrand">ایجاد برند جدید</a></li>
            </ul>
        </li>
        <li>
            <a asp-controller="Product" asp-action="ProductCategory" asp-area="Admin"><i class="zmdi zmdi-menu"></i><span> مدیریت دسته بندی ها </span></a>
        </li>

        <li>
            <a asp-controller="Product" asp-action="Index" asp-area="Admin"><i class="zmdi zmdi-shopping-basket"></i><span> محصولات </span></a>
        </li>
       
        <li>
            <a asp-controller="Ticket" asp-action="filterTicket" asp-area="Admin"><i class="ti-ticket"></i><span> تیکت ها </span></a>
        </li>
        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-settings "></i> <span> تنظیمات سایت </span> <span class="menu-arrow"></span></a>
            <ul class="list-unstyled">
                <li><a asp-controller="SiteSetting" asp-area="Admin" asp-action="SiteInformation">اطلاعات سایت</a></li>
                <li><a asp-controller="SiteSetting" asp-area="Admin" asp-action="EditSiteSetting">ویرایش اطلاعات سایت</a></li>
                <li><a asp-controller="SiteSetting" asp-area="Admin" asp-action="ListSlider">اسلایدر صفحه</a></li>
                <li><a asp-controller="SiteSetting" asp-area="Admin" asp-action="CreateSlider">ایجاد اسلایدر</a></li>


            </ul>
        </li>
        <li>
            <a asp-controller="ContactUs" asp-action="Index" asp-area="Admin"><i class="fa fa-phone"></i><span> لیست تماس ها </span></a>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>
<!-- Sidebar -->